name: Publish to JSR

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run tests
        run: deno task test

      - name: Type check
        run: deno task check

      - name: Lint
        run: deno task lint

      - name: Publish to JSR
        run: deno publish
